# ─────────────────────────────────────────────────────────────────────────────
# dondutra dotfiles — Alacritty configuration
# yt:    youtube.com/@arkty
# github: github.com/dondutra
# Note: Free to use as long as this header remains, or there is an explicit
#       mention of the creator (dondutra).
# ─────────────────────────────────────────────────────────────────────────────

# -----------------------------
# General
# -----------------------------
[general]
live_config_reload = true   # auto-reload config on save

# -----------------------------
# Window
# -----------------------------
[window]
padding = { x = 8, y = 8 }  # inner padding in pixels

# -----------------------------
# Font
# -----------------------------
[font]
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
bold   = { family = "UbuntuMono Nerd Font", style = "Bold" }
italic = { family = "UbuntuMono Nerd Font", style = "Italic" }
size = 20.0

# -----------------------------
# Colors — primary
# -----------------------------
[colors.primary]
background = "#0b0b0d"   # near-black gray
foreground = "#e6e6ea"   # light gray, high legibility

# -----------------------------
# Colors — ANSI palette (subtle)
# -----------------------------
[colors.normal]
black   = "#1e1f22"
red     = "#e27d88"   # soft red
green   = "#98c7a1"   # soft green
yellow  = "#d9c387"   # soft amber
blue    = "#8aa8e6"   # desaturated blue
magenta = "#b49ad9"   # gentle lilac (not dominant)
cyan    = "#8ec9d3"   # soft cyan
white   = "#cfcfd4"

[colors.bright]
black   = "#2c2d31"
red     = "#f0a0a9"
green   = "#b7e0bf"
yellow  = "#ead8a8"
blue    = "#a8c1ff"
magenta = "#dac4f7"   # periwinkle; used when apps request bold
cyan    = "#b7e6ee"
white   = "#f2f2f4"

# -----------------------------
# Colors — cursor & selection
# -----------------------------
[colors.cursor]
cursor = "#dac4f7"    # periwinkle cursor
text   = "#0b0b0d"

[colors.selection]
background = "#2c2d31"
text       = "#e6e6ea"

# If you prefer bold text to use the "bright" row of the palette:
# draw_bold_text_with_bright_colors = true
