[general]
live_config_reload = true

[window]
padding = { x = 8, y = 8 }

[font]
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
bold   = { family = "UbuntuMono Nerd Font", style = "Bold" }
italic = { family = "UbuntuMono Nerd Font", style = "Italic" }
size = 16.0

[colors.primary]
background = "#0b0b0d"   # gris casi negro
foreground = "#e6e6ea"   # gris claro legible

# Paleta ANSI sobria (sin lilas dominantes)
[colors.normal]
black   = "#1e1f22"
red     = "#e27d88"   # rojo suave
green   = "#98c7a1"   # verde suave
yellow  = "#d9c387"   # ámbar suave
blue    = "#8aa8e6"   # azul desaturado
magenta = "#b49ad9"   # lila suave (no protagonista)
cyan    = "#8ec9d3"   # cian suave
white   = "#cfcfd4"

[colors.bright]
black   = "#2c2d31"
red     = "#f0a0a9"
green   = "#b7e0bf"
yellow  = "#ead8a8"
blue    = "#a8c1ff"
magenta = "#dac4f7"   # periwinkle (para negritas si algún programa lo pide)
cyan    = "#b7e6ee"
white   = "#f2f2f4"

[colors.cursor]
cursor = "#dac4f7"    # periwinkle para el cursor
text   = "#0b0b0d"

[colors.selection]
background = "#2c2d31"
text       = "#e6e6ea"

# Si quieres que el texto en negrita use la fila "bright":
# draw_bold_text_with_bright_colors = true
