[Icon Theme]
Name=plasma-monochrome-icons
Inherits=Papirus-Dark,breeze-dark,Cosmic,Adwaita,hicolor
Comment=plasma-monochrome-icons by dirn

DisplayDepth=32
FollowsColorScheme=true
Example=x-directory-normal

KDE-Extensions=.svg

Directories=actions/16,apps/16,apps/scalable,categories/16,categories/scalable,devices/16,devices/scalable,emblems/scalable,places/16,places/scalable,places/symbolic,mimetypes/scalable,status/16,status/scalable,preferences/16,preferences/scalable

[actions/16]
Context=Actions
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[apps/16]
Size=16
Context=Applications
MinSize=16
MaxSize=28
Type=Scalable

[apps/scalable]
Size=128
Context=Applications
Type=Scalable
MinSize=29
MaxSize=512

[categories/16]
Size=16
Context=Categories
MinSize=16
MaxSize=32
Type=Scalable

[categories/scalable]
Context=Categories
Size=16
MinSize=33
MaxSize=512
Type=Scalable

[devices/16]
Size=128
Context=Devices
Type=Scalable
MinSize=16
MaxSize=32

[devices/scalable]
Size=128
Context=Devices
Type=Scalable
MinSize=33
MaxSize=128

[emblems/scalable]
Size=128
Context=Actions
Type=Scalable
MinSize=16
MaxSize=128

[places/16]
Context=Places
Size=64
MinSize=16
MaxSize=32
Type=Scalable

[places/scalable]
Context=Places
Size=64
MinSize=33
MaxSize=512
Type=Scalable

[mimetypes/scalable]
Size=512
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=512

[status/16]
Size=16
Context=Status
MinSize=16
MaxSize=32
Type=Scalable

[status/scalable]
Context=Status
Size=64
MinSize=33
MaxSize=512
Type=Scalable

[preferences/16]
Size=64
Context=Applications
MinSize=16
MaxSize=32
Type=Scalable

[preferences/scalable]
Context=Applications
Size=64
MinSize=32
MaxSize=512
Type=Scalable
